### ISSUE TITLE
Add a CSS file to beautify it and make it more appealing.

### ISSUE THREAD

**Issue by pandayed** [xpandeyed/Analog-Clock#2]
I have not worked with css files ,so please help.

**Comment by bineetNaidu** [comment]
hey there, would u like me to work on this issue :smile:.

**Comment by HimangsKalita** [comment]
When I ran the index.html its showing blank white screen no clock I am not building it right?

**Comment by rajmunkhan** [comment]
@xpandeyed  I would like to work on this, please assign it to me.
